# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
	scheme: "testAutomation-REL", # Build your app
   	export_method: "app-store",
	export_options: {
	        provisioningProfiles: {
		 "com.dm.testAutomation" => "AppStore Distribution profile for testAutomation"
        	}
    	}
    )
    upload_to_testflight
  end

  desc "Release to the App Store"
  lane :release do
    build_app(
	scheme: "testAutomation-REL", # Build your app
   	export_method: "app-store",
	export_options: {
	        provisioningProfiles: {
		 "com.dm.testAutomation" => "AppStore Distribution profile for testAutomation"
        	}
    	}
    )
    upload_to_testflight(
      username: ENV['FASTLANE_USER'],
      app_specific_password: ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']
    )
  end
end