name: Fastlane Build and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install dependencies
      run: bundle install

    - name: Decode and save provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/appstore.mobileprovision
      env:
        PROVISIONING_PROFILE: ${{ secrets.DISTRIB_PROV_PROFILE }}

    - name: Decode and save certificate
      run: echo "$CERTIFICATE_P12" | base64 --decode > $RUNNER_TEMP/certificate.p12
      env:
        CERTIFICATE_P12: ${{ secrets.IOS_DISTRIBUTION_CERT }}

    - name: Set up keychain and import certificate
      run: |
       # Enable detailed logging for debugging
         set -x
       # Generate a random password for the keychain
         export KEYCHAIN_PASSWORD=$(openssl rand -base64 32)
       # Create a new keychain with the generated password
         security create-keychain -p "$KEYCHAIN_PASSWORD" /tmp/build.keychain
       # Set the new keychain as the default
         security default-keychain -s /tmp/build.keychain
       # Unlock the keychain
         security unlock-keychain -p "$KEYCHAIN_PASSWORD" /tmp/build.keychain
       # Set permissions on the keychain
         sudo chmod -R 777 /tmp/build.keychain
       # Import the certificate into the keychain
         security import $RUNNER_TEMP/certificate.p12 -k /tmp/build.keychain -P "" -T /usr/bin/codesign
       # Allow codesign to access the keychain
         security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" /tmp/build.keychain

    - name: Build and archive app
      run: xcodebuild -project testAutomation.xcodeproj -scheme testAutomation-REL -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $PWD/build/testAutomation-REL.xcarchive

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath $PWD/build/testAutomation-REL.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build/
